name: CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.4'

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build project
        run: make build

      - name: Generate handlers from OpenAPI spec
        run: make generate-api

      - name: Check for uncommitted changes
        run: git diff --exit-code || (echo '❌ Found uncommitted changes. Please run `make generate-handlers` and commit the result.' && exit 1)

      - name: Run tests
        run: make test
